FROM node:10.16-buster-slim as builder

RUN apt-get update && apt-get install -y \
  build-essential \
  curl \
  bash \
  imagemagick \
  git \
  && rm -rf /var/lib/apt/lists/*
ENV APP_PATH /usr/src/fe-landingpage
WORKDIR $APP_PATH

COPY frontend/landingpage/package.json package.json
RUN npm install
COPY frontend/landingpage .
RUN npm run build

FROM nginx

RUN apt-get update -qq && apt-get -y install apache2-utils software-properties-common \
      gpg wget ca-certificates vim \
      && rm -rf /var/lib/apt/lists/*

# RUN add-apt-repository ppa:certbot/certbot -y
# RUN apt-get update
# RUN apt-get install python-certbot-nginx -y

ENV RAILS_ROOT /usr/src/shop
WORKDIR $RAILS_ROOT

RUN mkdir log
COPY nginx_stag.conf /tmp/docker.nginx

RUN envsubst '$RAILS_ROOT' < /tmp/docker.nginx > /etc/nginx/conf.d/default.conf
# RUN echo "0 12 * * * /usr/bin/certbot renew --quiet" > /var/spool/cron/crontabs/root

COPY --from=builder /usr/src/fe-landingpage /usr/src/fe-landingpage/

EXPOSE 80 443

CMD [ "nginx", "-g", "daemon off;" ]
